const products = [
  {
    id: 1,
    name: "Wireless Mouse",
    brand: "Logitech",
    categoryId: 1,
    price: 25.99,
    stock: 120,
    rating: 4.6,
    isAvailable: true,
  },
  {
    id: 2,
    name: "Mechanical Keyboard",
    brand: "Redragon",
    categoryId: 1,
    price: 59.99,
    stock: 75,
    rating: 4.8,
    isAvailable: true,
  },
  {
    id: 3,
    name: "Gaming Headset",
    brand: "HyperX",
    categoryId: 1,
    price: 89.99,
    stock: 40,
    rating: 4.7,
    isAvailable: true,
  },
  {
    id: 4,
    name: "Smart Watch",
    brand: "Samsung",
    categoryId: 1,
    price: 199.99,
    stock: 30,
    rating: 4.5,
    isAvailable: true,
  },
  {
    id: 5,
    name: "Running Shoes",
    brand: "Nike",
    categoryId: 2,
    price: 120.0,
    stock: 55,
    rating: 4.4,
    isAvailable: true,
  },
  {
    id: 6,
    name: "Backpack",
    brand: "American Tourister",
    categoryId: 2,
    price: 49.99,
    stock: 90,
    rating: 4.3,
    isAvailable: true,
  },
  {
    id: 7,
    name: "Bluetooth Speaker",
    brand: "JBL",
    categoryId: 1,
    price: 79.99,
    stock: 65,
    rating: 4.6,
    isAvailable: true,
  },
  {
    id: 8,
    name: "Water Bottle",
    brand: "Milton",
    categoryId: 3,
    price: 15.5,
    stock: 200,
    rating: 4.2,
    isAvailable: true,
  },
  {
    id: 9,
    name: "Laptop Stand",
    brand: "UGREEN",
    categoryId: 1,
    price: 34.99,
    stock: 80,
    rating: 4.7,
    isAvailable: true,
  },
  {
    id: 10,
    name: "USB-C Charger",
    brand: "Anker",
    categoryId: 1,
    price: 29.99,
    stock: 150,
    rating: 4.8,
    isAvailable: true,
  },
  {
    id: 11,
    name: "Laptop RAM",
    brand: "UGREEN",
    categoryId: 1,
    price: 34.99,
    stock: 80,
    rating: 4.7,
    isAvailable: true,
  },
];

export const categoryList = [
  {
    id: 1,
    name: "Electronics",
  },
  {
    id: 2,
    name: "Fashion",
  },
  {
    id: 3,
    name: "Home & Kitchen",
  },
  {
    id: 4,
    name: "Books",
  },
  {
    id: 5,
    name: "Sports",
  },
  {
    id: 6,
    name: "Beauty",
  },
  {
    id: 7,
    name: "Toys",
  },
  {
    id: 8,
    name: "Groceries",
  },
  {
    id: 9,
    name: "Furniture",
  },
  {
    id: 10,
    name: "Automotive",
  },
];

export default products;
